# Generated by Django 3.0.5 on 2024-02-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetails',
            old_name='department',
            new_name='contact',
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='empdept',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
