# Generated by Django 3.0.5 on 2024-02-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0002_auto_20240211_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='gender',
        ),
    ]
