# Generated by Django 4.0.3 on 2024-02-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0004_alter_employeedetails_empcode_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='empcode',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
