# Generated by Django 5.0.2 on 2024-02-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0005_alter_employeedetails_empcode_delete_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='empcode',
            field=models.IntegerField(null=True),
        ),
    ]
