# Generated by Django 5.0.2 on 2024-03-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0008_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='empcode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
