# Generated by Django 5.0.2 on 2024-04-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0015_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='end_time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
