# Generated by Django 5.0.2 on 2024-04-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0016_remove_attendance_end_time_attendance_is_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
