# Generated by Django 5.0.2 on 2024-04-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0017_attendance_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_leave',
            name='total_days',
            field=models.IntegerField(null=True),
        ),
    ]
