# Generated by Django 5.0.2 on 2024-04-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0018_employee_leave_total_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
