# Generated by Django 5.0.2 on 2024-04-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0019_salary_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='month',
            field=models.CharField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='salary',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
