# Generated by Django 5.0.2 on 2024-05-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0022_remove_skillset_user_skillset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='contact',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
